### ISSUE TITLE
ID3 Tags

### ISSUE THREAD

**Issue by bonanza123** [jgibbon/Talefish#11]
Is it possible to add support for ID3 tags? I have the problem that several audio files are only numbered, but contain tags with titles etc. In talefish it's currently difficult to select the proper song therefore.

**Comment by jgibbon** [comment]
Hi!
Because Talefish does not use the Sailfish media library in favour of being directory-based, none of the file infos are available without using external libraries. If someone had the time to make a working pull request with (optional!) ID3 info usage, I'd gladly check that out.

In the mean time I'd recommend for you to use some renaming tool to make your file names a bit more readable. Assuming Desktop Linux, something like [id3ren](http://manpages.ubuntu.com/manpages/zesty/man1/id3ren.1.html) might do the trick.

**Comment by jgibbon** [comment]
Short update on this: 
If mediainfo is installed, it is now used to gather file durations much more quickly than QML could. 
It should be possible to use it for title information, as well, in the future. 
Apart from some code for this, there are some more settings needed, though, because it'd be confusing if you get different results opening files just because another application is installed.

cheers!

**Comment by jgibbon** [comment]
ID3 tags are now (v0.1-1) displayed in the directory chooser if they are read correctly. It's in the tiny meta data line, but should help in finding the correct file to open. Thanks for the suggestion!

cheers!
