### ISSUE TITLE
Special characters in ID3 tag of eposode title are not decoded properly

### ISSUE THREAD

**Issue by dimpflmoser** [jgibbon/Talefish#22]
Audio files with special characters such as German umlauts, e.g. äöü or ß in ther ID3 tags are not decoded properly. I think it was shown properly in the previous version.
(Actually UnPlayer does the same.)

**Comment by jgibbon** [comment]
Thanks for checking it out!
Previous versions only showed directory/file names in most places, so that shouldn't have been an issue as long as the file name looked ok.

I have tested (some) umlauts and didn't find any problems with my files:
[example screen shot with umlauts](https://i.imgur.com/vZe189m.png)

I'd like to investigate this a bit further, though: 
- Does the system media player display correct characters?
- Are you sure the meta data isn't somehow badly formatted/encoded?
- Is it in mp3 files?
- Can you upload an affected file for me to check? Preferably where you can delete it after I've got it.

Cheers!

**Comment by dimpflmoser** [comment]
Ok, checked one of those files on the (Linux) desktop with VLC and it has the same issue there. It seems that the encoding got wrong, not sure whether that is on content creation or that my download mangled the encoding. Interestingly the tilte is mangled and the comment is alright. ;-)

Never mind I would regard that as a 'works-for-me' issue and suggest to close it.
If you would like to checkout the file I can send you a download link from the public radio repository

**Comment by jgibbon** [comment]
Glad to hear, to be honest: 
Encoding things are never, ever fun to fix – but if it's wrong even in vlc, I can happily live with it, as well. :)

Again, thanks for taking the time to report possible errors, it is very much appreciated.
Amazingly few people do.

Cheers
