### ISSUE TITLE
Progress bar is lost when you switch beteen landscape and portrait mode

### ISSUE THREAD

**Issue by dimpflmoser** [jgibbon/Talefish#27]

**Comment by jgibbon** [comment]
Hi,
thank you for taking the time to report this bug. Sadly I wasn't able to reproduce the issue on multiple devices, so I'd like you to provide some more info to get to the bottom of it:
 - Which device are you using?
 - Which version of SailfishOS are you on?
 - Can you provide some screenshots? (You could use some public domain audio book for display purposes if you're hesitant to share your listening habits, for example from https://librivox.org/search?q=moby%20dick&search_form=advanced )
 - Unlikely, but could it be that you've somehow disabled the (playlist) progress bar in appearance settings or have just one file opened? In both cases, the bar for total progress is hidden. That wouldn't happen when switching orientation, though.

cheers!

**Comment by jgibbon** [comment]
Hi @dimpflmoser 
could you also please recheck with the current release on openrepos? 
Perhaps, for some reason, the underlying QML Multimedia logic went into error mode (files deleted? flash storage problem?). When an error is detected, the progress bars will also be hidden. I've changed the error handling a bit with the recent release, so that may fix your problem, as well.

cheers!

**Comment by dimpflmoser** [comment]
Sorry, forgot to reply earlier. Couldn't reproduce this error anymore with 0.5-1.
Actually I think it happened each time when I installed an update before I restarted the app.

I suggest to close this issue  woll reopen it if it comes again

**Comment by jgibbon** [comment]
Awesome, thanks for letting me know, I'll close it. 
Cheers!
