### ISSUE TITLE
[Enhancement] Provide separate option for open and enqueue in pulldown menu

### ISSUE THREAD

**Issue by dimpflmoser** [jgibbon/Talefish#28]
We had this option in the old version and I could easily choose to open or enqueue new tracks. Now I need to go to many steps to switch between the modes and even need to remember next time which mode is active.

**Comment by dimpflmoser** [comment]
Ok, just saw that on top of Open/Enqueue dialogue it shows `Open all files` or`Enqueue all files` depending on which option is active. Haven't recognised that before. 
Anyway switching between both options is rather cumbersome.

**Comment by jgibbon** [comment]
Sorry I haven't found the time to reply to this earlier.

It was actually a deliberate decision to keep the PullDown-Menu smaller while still enabling enqueuing at all. I recognize it being not easy to tell apart the active mode – so additionally to the different header message, there should be a small "+" icon next to the settings button in enqueue mode, as well.
Also please note you can set Talefish to remember the last used mode (either via "more options" when opening files or in the normal options in the "open files" section) by using the "remember enqueue mode" option. Changing the mode should also be only two taps on the screen which, combined with the setting mentioned before, is quite manageable in my opinion for most use cases.

I hope you can get used to this because I already put in all those workarounds to make the menu smaller than it was before v0.2 while generally enabling "enqueue" without explicitly having to activate it in the options. I think those are acceptable compromises the way they are now. Feel free to re-open if you have additional ideas to make them more useable without sacrificing too much space on the screen, though. I'm happy to think them through.

cheers!
