### ISSUE TITLE
Playback speed is somtimes not set when jumping to next/previous audio

### ISSUE THREAD

**Issue by dimpflmoser** [jgibbon/Talefish#37]
Possibly related to #33 

Since SFOS 4.2 supports pitch correction when changing playback speed I started to use this option. However it happens some times (rather often) that when I jump to the next audio file (podcast) the playback speed is not set. If I jump back and forth sometimes it's set correctly but most often it doesn't fix the issue. I.e. I need to open the app, open Options and change the playback speed.

**Comment by jgibbon** [comment]
Hi, thanks for reporting this issue. 
I have been able to reproduce this problem and have expanded the workaround that was already in place.
It may just be a typical "works for me" situation, so please be so kind and test the newest pre-release build here on github.
If the issue persists, please feel free to re-open this one, otherwise a comment would also be appreciated, so I can prepare a "real" release.
https://github.com/jgibbon/Talefish/releases/tag/pre-0.8-1

cheers!

**Comment by dimpflmoser** [comment]
Thanks for the fix.
The new version pre-0.8-1 did play new files with the speed that was set in the GUI. So this seems to be fixed.
However I realised that if I have several files in a directory and if I choose to play the whole directory playback stops after each file and I need to press play to continue. Did I (accidently) set an option in the GUI or is that a new issue?
Should I create a new issue for that?
